AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template for RDS MySQL.'

Parameters:
  VpcId: 
    Description: VPC id 
    Type: String
    Default: vpc-02627d93614f7bc15

  PubSub1:
    Description: Subnet Id where instance will create 
    Type: String
    Default: subnet-0b0c3d3e9b65e32b2
  
  WPInstanceType:
    Type: String
    Default: t2.micro

  AMI:
    Type: String
    Default: ami-0a3c3a20c09d6f377

Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "cfn-test-sg"
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22 and http access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: '0.0.0.0/0'

  
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref WPInstanceType
      SecurityGroupIds: 
        - !Ref EC2SecurityGroup
      KeyName: "mac-new"
      ImageId: !Ref AMI
      SubnetId: !Ref PubSub1
      UserData:
        Fn::Base64: |
          #!/bin/bash

          sudo dnf install -y wget httpd php unzip httpd-tools php-cli php-json php-gd php-mbstring php-pdo php-xml php-mysqlnd php-pecl-zip php-common
          sudo dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          sudo dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
          sudo yum --enablerepo=remi,remi-8.0
          sudo systemctl start httpd
          sudo systemctl enable httpd

          wget https://wordpress.org/latest.zip
          unzip latest.zip
          mv wordpress/* /var/www/html/
          cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php

          sed -i 's/database_name_here/wordpress/g' /var/www/html/wp-config.php
          sed -i 's/username_here/wordpressuser/g' /var/www/html/wp-config.php
          sed -i 's/password_here/password/g' /var/www/html/wp-config.php
          
          chown -R apache:apache /var/www/html/
          chcon -R -t httpd_sys_content_t /var/www/html 
          sed -i 's/Enforcing/disabled/g' /etc/selinux/config



