AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template for RDS MySQL.'

Parameters:
  VpcId: 
    Description: Existing VPC after its creation 
    Type: String
    Default: vpc-02627d93614f7bc15

  PubSub1:
    Description: Existing subnet after its creation
    Type: String
    Default: subnet-0b0c3d3e9b65e32b2
  
  WPInstanceType:
    Type: String
    Default: t2.micro

  AMI:
    Type: String
    Default: ami-0a3c3a20c09d6f377

Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "cfn-test-sg"
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22 and http access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: '0.0.0.0/0'

  
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref WPInstanceType
      SecurityGroupIds: 
        - !Ref EC2SecurityGroup
      KeyName: "mac-new"
      ImageId: !Ref AMI
      SubnetId: !Ref PubSub1
      UserData:
        Fn::Base64: |
          #!/bin/bash

          sudo dnf install httpd php php-mysqlnd php-fpm php-opcache php-curl php-json php-gd php-xml php-mbstring php-zip -y
          sudo systemctl start httpd
          sudo systemctl enable httpd

          sudo wget https://wordpress.org/latest.zip
          sudo unzip latest.zip
          sudo mv wordpress/* /var/www/html/
          sudo chown -R apache:apache /var/www/html/
          sudo cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php

          sudo sed -i 's/database_name_here/wordpress/g' /var/www/html/wp-config.php
          sudo sed -i 's/username_here/wordpressuser/g' /var/www/html/wp-config.php
          sudo sed -i 's/password_here/password/g' /var/www/html/wp-config.php
          



